Repository XtremeWave/FinalSuspect, pull requests merged in 2025-03, with the labels that each got.

#27 Update Readme
  .github/ISSUE_TEMPLATE/FeatureRequest_en.yaml
  .github/ISSUE_TEMPLATE/FeatureRequest_zh.yaml
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  README_zh.md
Labels: Non-primary

#34 Fix bug
  Assets/ModNews/Brazilian/FS.v1.1_20250216.txt
  Assets/ModNews/Dutch/FS.v1.1_20250216.txt
  Assets/ModNews/English/FS.v1.1_20250216.txt
  Assets/ModNews/Filipino/FS.v1.1_20250216.txt
  Assets/ModNews/French/FS.v1.1_20250216.txt
  Assets/ModNews/German/FS.v1.1_20250216.txt
  Assets/ModNews/Irish/FS.v1.1_20250216.txt
  Assets/ModNews/Italian/FS.v1.1_20250216.txt
  Assets/ModNews/Japanese/FS.v1.1_20250216.txt
  Assets/ModNews/Korean/FS.v1.1_20250216.txt
  Assets/ModNews/Latam/FS.v1.1_20250216.txt
  Assets/ModNews/Portuguese/FS.v1.1_20250216.txt
  Assets/ModNews/Russian/FS.v1.1_20250216.txt
  Assets/ModNews/SChinese/FS.v1.1_20250216.txt
  Assets/ModNews/SChinese/FeaturesIntroduction.v1.1.txt
  Assets/ModNews/Spanish/FS.v1.1_20250216.txt
  Assets/ModNews/TChinese/FS.v1.1_20250216.txt
  Assets/ModNews/TChinese/FeaturesIntroduction.v1.1.txt
  FinalSuspect/Modules/Resources/VersionChecker.cs
  FinalSuspect/Patches/System/LoadPatch.cs
Labels: Bug

#24 添加了房间存在时间检测器,方便根据你的需求寻找对应的房间
  Assets/Languages/Brazilian.yaml
  Assets/Languages/Dutch.yaml
  Assets/Languages/English.yaml
  Assets/Languages/Filipino.yaml
  Assets/Languages/Franch.yaml
  Assets/Languages/German.yaml
  Assets/Languages/Irish.yaml
  Assets/Languages/Italian.yaml
  Assets/Languages/Japanese.yaml
  Assets/Languages/Korean.yaml
  Assets/Languages/Latam.yaml
  Assets/Languages/Portuguese.yaml
  Assets/Languages/Russian.yaml
  Assets/Languages/SChinese.yaml
  Assets/Languages/Spanish.yaml
  Assets/Languages/TChinese.yaml
  Patches/Systemupload/LobbyListPatch.cs
Labels: Feature

#35 Some Changes
  Assets/ModNews/Brazilian/FS.v1.1_20250216.txt
  Assets/ModNews/Dutch/FS.v1.1_20250216.txt
  Assets/ModNews/English/FS.v1.1_20250216.txt
  Assets/ModNews/Filipino/FS.v1.1_20250216.txt
  Assets/ModNews/French/FS.v1.1_20250216.txt
  Assets/ModNews/German/FS.v1.1_20250216.txt
  Assets/ModNews/Irish/FS.v1.1_20250216.txt
  Assets/ModNews/Italian/FS.v1.1_20250216.txt
  Assets/ModNews/Japanese/FS.v1.1_20250216.txt
  Assets/ModNews/Korean/FS.v1.1_20250216.txt
  Assets/ModNews/Latam/FS.v1.1_20250216.txt
  Assets/ModNews/Portuguese/FS.v1.1_20250216.txt
  Assets/ModNews/Russian/FS.v1.1_20250216.txt
  Assets/ModNews/SChinese/FS.v1.1_20250216.txt
  Assets/ModNews/SChinese/FeaturesIntroduction.v1.1.txt
  Assets/ModNews/Spanish/FS.v1.1_20250216.txt
  Assets/ModNews/TChinese/FS.v1.1_20250216.txt
  Assets/ModNews/TChinese/FeaturesIntroduction.v1.1.txt
  FinalSuspect/Modules/Resources/VersionChecker.cs
  FinalSuspect/Patches/Game_Vanilla/NotificationPopperPatch.cs
  FinalSuspect/Patches/System/LoadPatch.cs
  FinalSuspect/Resources/Configs/BanWords/SChinese.txt
  FinalSuspect/main.cs
Labels: Develop, Announcement

#38 非关键文件优化
  .github/ISSUE_TEMPLATE/BugReport_en.yaml
  .github/ISSUE_TEMPLATE/BugReport_zh.yaml
  .github/ISSUE_TEMPLATE/FeatureRequest_en.yaml
  .github/ISSUE_TEMPLATE/FeatureRequest_zh.yaml
  CODE_OF_CONDUCT.md
  README.md
  README_zh.md
Labels: Non-primary
